### ISSUE TITLE
Task Model 的 done event 允許轉換的狀態有誤

### ISSUE THREAD

**Issue by tka** [kaichi1216/test18#19]
https://github.com/kaichi1216/test18/blob/1376513657e627881d241a1bd5af6e300d711845/app/models/task.rb#L21

這邊是不是應該是下面這樣才對，中間不需要 `,`

```
 transitions from: %i[pending processing], to: :solved 
```

**Comment by kaichi1216** [comment]
疑！ 我剛有試過 有沒有加， 都可以運行耶！！有錯請大大指導

**Comment by tka** [comment]
```
%i[pending, processing]  會是　[:"pending,", :processing]

但是

%i[pending processing] 會是 [:pending, :processing]
```
所以 pending 的狀態下，真的可以透過 event 轉成 solved 嗎

**Comment by kaichi1216** [comment]
我了解意思了 剛測試原寫法pending 轉 solved 會出錯，修改後 就可以轉換了，謝謝大大的提點！！
